/**
 * The seeded Week 8 scenario: Westfield Wildcats (6–1, #2) host Central Catholic
 * (7–0, #1), Friday Oct 16. Transcribed from the accepted UI-3 prototype.
 *
 * This is fictional data for the Simulation Experience. No real student-athletes.
 */

import type {
  FilmClip,
  PracticeDay,
  ScoutingHypothesis,
  Stage,
  WeekScenario,
} from './types.ts';
import { GAME_PLAN_ANSWERS, GAME_PLAN_OBJECTIVES } from './gamePlanScenario.ts';

const STAGES: readonly Stage[] = [
  {
    id: 'evidence',
    day: 'MON',
    title: 'Film & evidence',
    date: 'Oct 12',
    surface: 'Film Room',
  },
  {
    id: 'plan',
    day: 'TUE',
    title: 'Game plan',
    date: 'Oct 13',
    surface: 'Game Plan',
  },
  {
    id: 'practice',
    day: 'WED',
    title: 'Practice plan',
    date: 'Oct 14',
    surface: 'Practice',
  },
  {
    id: 'disruption',
    day: 'THU',
    title: 'Depth & availability',
    date: 'Oct 15',
    surface: 'Depth Chart',
  },
  {
    id: 'friday',
    day: 'FRI',
    title: 'Game night',
    date: 'Oct 16',
    surface: 'Decision Room',
  },
  {
    id: 'review',
    day: 'SAT',
    title: 'Decision review',
    date: 'Oct 17',
    surface: 'Review',
  },
];

/** Fixed practice periods and opponent-plan capacity from canonical UI-3. */
const PRACTICE_DAYS: readonly PracticeDay[] = [
  {
    id: 'MON',
    date: 'Oct 12',
    pads: 'Helmets',
    duration: '1h 15m',
    capacity: 2,
    contact: false,
    note: 'Install day. Nothing live.',
    fixed: [
      { minutes: 10, name: 'Special teams walk-through' },
      { minutes: 20, name: 'Individual' },
      { minutes: 25, name: 'Install — four new plays' },
      { minutes: 20, name: 'Team walk-through' },
    ],
  },
  {
    id: 'TUE',
    date: 'Oct 13',
    pads: 'Full pads',
    duration: '1h 30m',
    capacity: 3,
    contact: true,
    note: 'The only live-contact window left this week.',
    fixed: [
      { minutes: 20, name: 'Individual' },
      { minutes: 20, name: 'Inside run' },
      { minutes: 15, name: 'Seven-on-seven' },
      { minutes: 25, name: 'Team period — live' },
    ],
  },
  {
    id: 'WED',
    date: 'Oct 14',
    pads: 'Shells',
    duration: '1h 20m',
    capacity: 2,
    contact: false,
    note: 'Shoulder pads, thud tempo. Nobody goes to the ground.',
    fixed: [
      { minutes: 15, name: 'Individual' },
      { minutes: 25, name: 'Situational team' },
      { minutes: 15, name: 'Red zone' },
      { minutes: 10, name: 'Two-minute' },
    ],
  },
  {
    id: 'THU',
    date: 'Oct 15',
    pads: 'Walk-through',
    duration: '55m',
    capacity: 1,
    contact: false,
    note: 'Short day. Legs back under them for Friday.',
    fixed: [
      { minutes: 10, name: 'Individual' },
      { minutes: 20, name: 'Special teams — all four units' },
      { minutes: 20, name: 'Team polish' },
      { minutes: 5, name: 'Curfew review' },
    ],
  },
];

const HYPOTHESES: readonly ScoutingHypothesis[] = [
  {
    id: 'h1',
    short: 'Power tendency',
    unit: 'Defense',
    statement:
      'On early downs from I-formation, Central runs power or counter toward the tight-end surface.',
    snaps: 41,
    games: 3,
    missing: 'No clips against an odd front — we have never shown them one.',
    confidence: 'Strong',
    confidenceWhy:
      '41 early-down snaps across three games, and the two contradicting clips both came from a two-score deficit.',
  },
  {
    id: 'h2',
    short: 'Sprint-out response',
    unit: 'Defense',
    statement:
      'After a negative play, or on 3rd & 4–7, Herrera sprint-outs to the boundary.',
    snaps: 14,
    games: 3,
    missing: 'Only one clip of it into a pressure look.',
    confidence: 'Moderate',
    confidenceWhy:
      '14 qualifying snaps is a thin sample, and three clips show him staying in the pocket instead.',
  },
  {
    id: 'h3',
    short: 'Cover 3 leverage',
    unit: 'Offense',
    statement:
      'Central’s early-down Cover 3 rotation leaves the trips-side flood window open.',
    snaps: 33,
    games: 3,
    missing:
      'We have not seen them play it against trips with a tight end attached.',
    confidence: 'Strong',
    confidenceWhy:
      '33 snaps of the same rotation, and the one contradiction was a check after a motion they may not see from us.',
  },
  {
    id: 'h4',
    short: 'Return-game threat',
    unit: 'Special Teams',
    statement:
      'Malone’s return unit flips field position when kicks land short of the goal line.',
    snaps: 6,
    games: 3,
    missing: 'Six returns total. Two opponents never kicked to him.',
    confidence: 'Low sample',
    confidenceWhy:
      'Only six returns exist. Three are alarming, none contradict, and that is not enough to call it a tendency.',
  },
];

/**
 * 32 tagged opponent clips. Tuple form mirrors the prototype's compact seed;
 * `toClip` widens it into the typed record the app consumes.
 */
type ClipTuple = readonly [
  id: string,
  side: FilmClip['side'],
  game: string,
  situation: string,
  personnel: string,
  formation: string,
  motion: string,
  concept: string,
  result: string,
  hypothesisId: string,
  relation: FilmClip['relation'],
  staffNote: string,
];

const CLIP_TUPLES: readonly ClipTuple[] = [
  [
    'c01',
    'DEF',
    'W7 vs Millbrook',
    '1st & 10 · own 28 · R hash',
    '11 pers',
    'Trips right',
    'None',
    'Cover 3 sky',
    'Comp +9',
    'h3',
    'sup',
    'Curl-flat defender chased the flat. The window behind him was open all night.',
  ],
  [
    'c02',
    'OFF',
    'W7 vs Millbrook',
    '3rd & 6 · +41 · L hash',
    '11 pers',
    'Doubles',
    'Nub shift',
    'Sprint-out right',
    'Comp +8',
    'h2',
    'sup',
    'Herrera was outside the tackle box in three steps.',
  ],
  [
    'c03',
    'ST',
    'W7 vs Millbrook',
    'Kickoff · 2Q',
    'KO unit',
    'Middle 8',
    '—',
    'Kick return right',
    '+38',
    'h4',
    'sup',
    'Malone hit the seam between the 3 and 4 lanes.',
  ],
  [
    'c04',
    'OFF',
    'W7 vs Millbrook',
    '1st & 10 · +34 · L hash',
    '21 pers',
    'I-Form Twin',
    'None',
    'Power right',
    '+7',
    'h1',
    'sup',
    'Both guards pull. Tight end sealed the end inside.',
  ],
  [
    'c05',
    'DEF',
    'W7 vs Millbrook',
    '2nd & 7 · own 44 · mid',
    '11 pers',
    'Trips left',
    'Jet',
    'Cover 3 buzz',
    'Inc',
    'h3',
    'sup',
    'Buzz safety was late over the top of the flood.',
  ],
  [
    'c06',
    'OFF',
    'W7 vs Millbrook',
    '3rd & 5 · own 31 · R hash',
    '11 pers',
    'Gun Trips',
    'None',
    'Pocket pass',
    'Comp +12',
    'h2',
    'con',
    'Stayed in the pocket here. Same down and distance, no sprint-out.',
  ],
  [
    'c07',
    'OFF',
    'W6 at Riverside',
    '2nd & 8 · own 39 · R hash',
    '21 pers',
    'I-Form',
    'None',
    'Counter left',
    '+4',
    'h1',
    'sup',
    'Backside guard wrapped. Malone cut off the wrap.',
  ],
  [
    'c08',
    'ST',
    'W6 at Riverside',
    'Kickoff · 3Q',
    'KO unit',
    'Middle 8',
    '—',
    'Kick return left',
    '+24',
    'h4',
    'sup',
    'Second-level lanes collapsed from the inside out.',
  ],
  [
    'c09',
    'OFF',
    'W6 at Riverside',
    '1st & 10 · own 22 · L hash',
    '21 pers',
    'I-Form Twin',
    'None',
    'Power right',
    '+11',
    'h1',
    'sup',
    'Third straight power to the tight-end side on first down.',
  ],
  [
    'c10',
    'DEF',
    'W6 at Riverside',
    '1st & 10 · +45 · R hash',
    '11 pers',
    'Trips right',
    'None',
    'Cover 3 sky',
    'Comp +14',
    'h3',
    'sup',
    'Same rotation, same hole. Riverside hit the flood twice.',
  ],
  [
    'c11',
    'OFF',
    'W6 at Riverside',
    '1st & 10 · own 35 · mid',
    '11 pers',
    'Gun Doubles',
    'None',
    'Zone read',
    '+3',
    'h1',
    'con',
    'Down 17 here. Four-wide on first down instead of power.',
  ],
  [
    'c12',
    'OFF',
    'W6 at Riverside',
    '2nd & 4 · +28 · L hash',
    '22 pers',
    'I-Form Heavy',
    'None',
    'Power right',
    '+6',
    'h1',
    'sup',
    'Extra tight end on the surface. The guard pull is identical.',
  ],
  [
    'c13',
    'DEF',
    'W6 at Riverside',
    '2nd & 6 · own 40 · R hash',
    '11 pers',
    'Trips right',
    'Orbit',
    'Quarters check',
    'Inc',
    'h3',
    'con',
    'They checked out of Cover 3 against orbit motion. Only clip of it.',
  ],
  [
    'c14',
    'OFF',
    'W6 at Riverside',
    '2nd & 12 · own 18 · R hash',
    '11 pers',
    'Doubles',
    'None',
    'Sprint-out right',
    'Comp +6',
    'h2',
    'sup',
    'Second and long after a tackle for loss. Sprint-out again.',
  ],
  [
    'c15',
    'OFF',
    'W5 vs East Ridge',
    '1st & 10 · own 41 · R hash',
    '21 pers',
    'I-Form',
    'None',
    'Power left',
    '+9',
    'h1',
    'sup',
    'Flipped the surface. Same play toward the tight end.',
  ],
  [
    'c16',
    'DEF',
    'W5 vs East Ridge',
    '1st & 10 · own 33 · L hash',
    '11 pers',
    'Trips left',
    'None',
    'Cover 3 sky',
    'Comp +11',
    'h3',
    'sup',
    'Corner sank, hook player widened. The flood again.',
  ],
  [
    'c17',
    'OFF',
    'W5 vs East Ridge',
    '3rd & 7 · +38 · mid',
    '11 pers',
    'Gun Trips',
    'None',
    'Pocket pass',
    'Sack',
    'h2',
    'con',
    'Held the pocket and took a sack instead of getting outside.',
  ],
  [
    'c18',
    'OFF',
    'W5 vs East Ridge',
    '3rd & 4 · own 47 · L hash',
    '11 pers',
    'Doubles',
    'None',
    'Sprint-out left',
    'Comp +5',
    'h2',
    'sup',
    'Third and medium. Boundary sprint-out, quick throw.',
  ],
  [
    'c19',
    'OFF',
    'W5 vs East Ridge',
    '1st & 10 · +19 · R hash',
    '21 pers',
    'I-Form Twin',
    'None',
    'Counter right',
    '+5',
    'h1',
    'sup',
    'Red zone, still counter to the tight-end surface.',
  ],
  [
    'c20',
    'DEF',
    'W5 vs East Ridge',
    '2nd & 8 · own 29 · R hash',
    '11 pers',
    'Trips right',
    'Jet',
    'Cover 3 buzz',
    'Comp +17',
    'h3',
    'sup',
    'The buzz defender is consistently a beat late.',
  ],
  [
    'c21',
    'OFF',
    'W5 vs East Ridge',
    '1st & 10 · own 47 · mid',
    '11 pers',
    'Gun Doubles',
    'None',
    'RPO glance',
    '+2',
    'h1',
    'con',
    'First down, no power. They were up 21 and killing clock.',
  ],
  [
    'c22',
    'ST',
    'W5 vs East Ridge',
    'Kickoff · 1Q',
    'KO unit',
    'Middle 8',
    '—',
    'Kick return right',
    '+41',
    'h4',
    'sup',
    'Third long return in three games. Only six returns exist.',
  ],
  [
    'c23',
    'OFF',
    'W7 vs Millbrook',
    '2nd & 3 · +12 · L hash',
    '22 pers',
    'I-Form Heavy',
    'None',
    'Power right',
    'TD',
    'h1',
    'sup',
    'Goal-line power. Same pull, extra tight end.',
  ],
  [
    'c24',
    'DEF',
    'W7 vs Millbrook',
    '3rd & 8 · own 36 · R hash',
    '11 pers',
    'Trips right',
    'None',
    'Cover 3 sky',
    'Comp +10',
    'h3',
    'sup',
    'Third down and they still played the same shell.',
  ],
  [
    'c25',
    'OFF',
    'W7 vs Millbrook',
    '2nd & 14 · own 25 · L hash',
    '11 pers',
    'Doubles',
    'None',
    'Sprint-out left',
    'Inc',
    'h2',
    'sup',
    'Behind schedule again. Boundary sprint-out again.',
  ],
  [
    'c26',
    'OFF',
    'W6 at Riverside',
    '1st & 10 · +44 · R hash',
    '21 pers',
    'I-Form',
    'Wing shift',
    'Power right',
    '+8',
    'h1',
    'sup',
    'The wing shifts late to the call side. Watch the shift.',
  ],
  [
    'c27',
    'DEF',
    'W7 vs Millbrook',
    '4th & 2 · +31 · mid',
    'Heavy',
    'Goal-line front',
    '—',
    'Run stuff',
    'TFL',
    '',
    'neu',
    'Good look at their heavy front. Does not speak to a tendency.',
  ],
  [
    'c28',
    'OFF',
    'W5 vs East Ridge',
    '3rd & 6 · own 22 · L hash',
    '11 pers',
    'Gun Trips',
    'None',
    'Pocket pass',
    'Comp +21',
    'h2',
    'con',
    'Their best throw of the night came from the pocket.',
  ],
  [
    'c29',
    'DEF',
    'W6 at Riverside',
    '1st & 10 · own 25 · L hash',
    '11 pers',
    'Trips left',
    'None',
    'Cover 3 sky',
    'Run +3',
    'h3',
    'sup',
    'Eighth man walked down on first down. The shell behind it is unchanged.',
  ],
  [
    'c30',
    'OFF',
    'W7 vs Millbrook',
    '1st & 10 · own 31 · R hash',
    '21 pers',
    'I-Form Twin',
    'None',
    'Power right',
    '+3',
    'h1',
    'sup',
    'Nine of eleven early-down I-formation runs went this direction.',
  ],
  [
    'c31',
    'OFF',
    'W6 at Riverside',
    '3rd & 5 · +36 · R hash',
    '11 pers',
    'Doubles',
    'None',
    'Sprint-out right',
    'Comp +7',
    'h2',
    'sup',
    'Fifth sprint-out on third and medium.',
  ],
  [
    'c32',
    'ST',
    'W6 at Riverside',
    'Punt · 4Q',
    'Punt unit',
    'Spread punt',
    '—',
    'Punt',
    'Net 41',
    '',
    'neu',
    'Their punt team is clean. Nothing obvious to attack.',
  ],
];

const WIDE_ONLY = new Set(['c03', 'c08', 'c22', 'c32']);
const TIGHT_ONLY = new Set(['c06', 'c11', 'c13', 'c17', 'c21', 'c27', 'c28']);

function anglesFor(id: string): FilmClip['angles'] {
  if (WIDE_ONLY.has(id)) return ['Wide'];
  if (TIGHT_ONLY.has(id)) return ['Tight'];
  return ['Tight', 'Wide'];
}

function toClip(tuple: ClipTuple): FilmClip {
  const [
    id,
    side,
    game,
    situation,
    personnel,
    formation,
    motion,
    concept,
    result,
    hypothesisId,
    relation,
    staffNote,
  ] = tuple;
  return {
    id,
    side,
    game,
    situation,
    personnel,
    formation,
    motion,
    concept,
    result,
    angles: anglesFor(id),
    hypothesisId: hypothesisId === '' ? null : hypothesisId,
    relation,
    staffNote,
  };
}

const CLIPS: readonly FilmClip[] = CLIP_TUPLES.map(toClip);

export const WEEK_8_SCENARIO: WeekScenario = {
  weekNumber: 8,
  program: {
    school: 'Westfield',
    mascot: 'Wildcats',
    record: '6–1',
    rank: '#2',
  },
  opponent: {
    name: 'Central Catholic',
    record: '7–0',
    rank: '#1',
    district: 'District 7-5A',
  },
  kickoff: 'Friday Oct 16, 7:30 PM',
  venue: 'Wildcat Stadium',
  stakes: 'Winner takes the district title and the home seed',
  stages: STAGES,
  hypotheses: HYPOTHESES,
  clips: CLIPS,
  objectives: GAME_PLAN_OBJECTIVES,
  answers: GAME_PLAN_ANSWERS,
  practiceDays: PRACTICE_DAYS,
  priorityCapacity: 3,
};
